
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: swiss-parcs-ims
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: swiss-parcs-ims
      MINIO_ROOT_PASSWORD: swiss-parcs-ims
      MINIO_DEFAULT_BUCKETS: swiss-parcs-ims
    volumes:
      - minio-data:/data

volumes:
    postgres-data:
      driver: local
    minio-data:
      driver: local
